### ISSUE TITLE
Password Validation on Registration page

### ISSUE THREAD

**Issue by ryanstrat** [Team-Goatr/Makerspace-Automation-Suite#107]
Passwords must be validated to Google's password rules to prevent a 400 error from Google.

**Comment by thomascoe** [comment]
I think the only "rule" here is it has to be at least 8 characters

**Comment by thomascoe** [comment]
Registration page and member page. In addition to passwords not matching, throw an error if the passwords are less than 8 characters

**Comment by thomascoe** [comment]
Fixed in master!
