### ISSUE TITLE
Admin Member page cannot be submitted with RFID field blank

### ISSUE THREAD

**Issue by ryanstrat** [Team-Goatr/Makerspace-Automation-Suite#110]

**Comment by thomascoe** [comment]
Also we may want to allow blank expiration date? People like Makerspace admins may not have an expiration date

**Comment by thomascoe** [comment]
Okay so in master now I reverted back to requiring an RFID. I tried to have it submit with an empty RFID number but I kept getting errors from G Suite, something about it it didn't like. So maybe we should just leave it at requiring RFID? Unless someone else can figure out the G Suite issue

**Comment by thomascoe** [comment]
Okay I removed the restriction from the form and just treated a stored 0 as an empty value

**Comment by ryanstrat** [comment]
Sounds like a good solution! I think the G Suite wrapper was treating the empty string as a null value, which ends up not being sent to the server. There's a special constant you can send that's documented. but I think this solution is fine
