### ISSUE TITLE
User Data in G Suite

### ISSUE THREAD

**Issue by jmbrown864** [Team-Goatr/Makerspace-Automation-Suite#14]
Design and set up user data schema in G Suite for Nonprofits.

**Comment by ryanstrat** [comment]
For Stripe payments, we will need to store the Customer ID: https://stripe.com/docs/subscriptions/quickstart

**Comment by thomascoe** [comment]
Added subscription management attributes to G Suite. These will need to be populated when we create users for each member
![image](https://cloud.githubusercontent.com/assets/274904/22132909/023c8cba-de8b-11e6-8808-0cfaa29465f4.png)

**Comment by thomascoe** [comment]
The Google Apps Admin SDK's Directory API can be used to create users programmatically (necessary for integration with the registration form we will build in wordpress) https://developers.google.com/admin-sdk/directory/v1/guides/manage-users

**Comment by ryanstrat** [comment]
For user login into wordpress, we will use a Single Sign On (SSO) system. Either a native google apps plugin or a SAML plugin. SAML would require enabling the SAML IDP in the Google admin console.

We found a [Google Apps Login](https://wordpress.org/plugins/miniorange-google-apps-login/installation/) plugin, but the support for it seems a bit sub-par. This [Google Apps Login plugin](https://wordpress.org/plugins/google-apps-login/) is good, but expensive.

There are also a variety of SAML plugins.

**Comment by thomascoe** [comment]
Found a PHP client library from Google. This will assist us with authentication for the wordpress registration page to be able to create a new user in G Suite. Using OAuth 2.0 for Web Server Applications: https://developers.google.com/api-client-library/php/auth/web-app

**Comment by thomascoe** [comment]
Ideally we wouldn't have to create wordpress users anymore during registration, they would only get their G Suite account and the Single Sign On system would allow them to log in, auto-creating a wordpress account if necessary

**Comment by thomascoe** [comment]
Migrating users into G Suite will probably be a manual process. Shouldn't be too awful since there are only ~100 active users (so 20 per person). Many users have stuff like full email addresses as their Wordpress username that will have to be manually resolved.
Steps:
1. Manually migrate users (including their stripe ID) into G Suite
2. Backup the restrict content pro/wordpress database
3. Wipe out all restrict content pro/wordpress users

**Comment by thomascoe** [comment]
Another useful link for using Google's PHP client:
https://github.com/google/google-api-php-client

**Comment by ryanstrat** [comment]
The SAML Plugin by Mini-Orange was implemented
