### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by danaalyse** [Team-Goatr/Makerspace-Automation-Suite#17]
Accept and process user registration forms.

**Comment by thomascoe** [comment]
In the 'thomas' branch, admin-pages/test/form.html provides an example form which submits to admin-pages/test/register.php. The php file provides the backend functionality of creating a Stripe customer and charging or subscribing them. So the payment functionality of the registration form is implemented.

**Comment by thomascoe** [comment]
register.php needs to be expanded to integrate with G Suite, creating a new G Suite user and saving the subscription type, expiration, status, and recurring (as well as the Stripe customer ID) as properties of that user. I think this G Suite integration into register.php is the only missing thing for this issue.

**Comment by thomascoe** [comment]
This G suite integration portion is essentially issue #19 so maybe this issue is complete?

**Comment by ryanstrat** [comment]
G Suite API can now register users. Currently with a placeholder password.
