### ISSUE TITLE
Accept Payments

### ISSUE THREAD

**Issue by danaalyse** [Team-Goatr/Makerspace-Automation-Suite#20]
Accept payments via one payment provider.

**Comment by thomascoe** [comment]
This is essentially implemented. The admin-pages/resources/StripeAPI.php file provides Stripe integration including functions to generate a "pay with card" button, create Stripe customers, charge Stripe customers, and subscribe Stripe customers.

The admin-pages/test folder in the 'thomas' branch contains form.html and register.php files that shows example usage of the functions provided by StripeAPI.php, including a demo that creates a Stripe customer and charges them or subscribes them depending on whether the recurring box is checked.
