### ISSUE TITLE
Email Alerts

### ISSUE THREAD

**Issue by ryanstrat** [Team-Goatr/Makerspace-Automation-Suite#23]
Set up email alerts for members for payment due dates.

**Comment by thomascoe** [comment]
Not sure how to do this for members with non-subscriptions.. For members with subscriptions, Stripe will hit our webhook when an invoice payment fails or succeeds, so we can notify via email when a failure happens. But I don't know what to do about non-recurring members.

**Comment by thomascoe** [comment]
For the purposes of this Epic, this is done. I opened issue #135 to handle the last issue relating to this.
