### ISSUE TITLE
Add user input password to registration form

### ISSUE THREAD

**Issue by cmowenby** [Team-Goatr/Makerspace-Automation-Suite#59]

**Comment by danaalyse** [comment]
For UI: 
2 input fields (pass and confirm)
JavaScript to confirm passwords match and reject otherwise

**Comment by ryanstrat** [comment]
Ryan: Backend to handle pre-hashed passwords, add crypto library and hash.

**Comment by thomascoe** [comment]
Works in master now. We don't hash, but sent over HTTPS so should be fine
