### ISSUE TITLE
Swap "Member Since" Column with "RFID Tag #"

### ISSUE THREAD

**Issue by cmowenby** [Team-Goatr/Makerspace-Automation-Suite#76]

**Comment by thomascoe** [comment]
As a part of this, we should also display "member since" in the edit member page along with the other more detailed info. I think this could still be somewhat useful to show somewhere.

**Comment by thomascoe** [comment]
Ryan please make G Suite backend change and add getter and setter to PHP file

**Comment by thomascoe** [comment]
Okay I've made the changes to the frontend in the **rfid-tag** branch and created the framework for the backend. Ryan please build off of this branch and implement the "getRfidTag" and "setRfidTag" functions in GSuiteAPI.php

**Comment by ryanstrat** [comment]
RFID functions are implemented, tested, and documented on rfid-tag branch.

**Comment by thomascoe** [comment]
PR merged
