### ISSUE TITLE
Add member tab to tab bar

### ISSUE THREAD

**Issue by danaalyse** [Team-Goatr/Makerspace-Automation-Suite#97]

**Comment by thomascoe** [comment]
Tab bar on main makerspace site. This may need to be done manually and not by the plugin?

**Comment by ryanstrat** [comment]
I'll take a stab at this

**Comment by ryanstrat** [comment]
The member page is added. I can't find a way to make it show up only if logged in, so I'm making it attempt login if clicked by a non-logged in user.

**Comment by thomascoe** [comment]
Yeah, the member page itself should redirect to log-in if you aren't logged in already. Currently it gives this error:
![image](https://cloud.githubusercontent.com/assets/274904/25104512/a4d6547c-238e-11e7-80db-bdedc6679d5d.png)

**Comment by ryanstrat** [comment]
I have the code to catch the error in the login branch, but I'm not really sure what to do with it. I haven't found a way to trigger a login. I'm going to spend more time digging through the code for the login plugin to do that.

**Comment by ryanstrat** [comment]
Thoughts on creating a new page that I can redirect to and the only content on the page is a login widget?

**Comment by thomascoe** [comment]
Just make a failure page modeled off failure.html

**Comment by thomascoe** [comment]
This redirects to the wordpress login page. It should probably redirect to the google login page instead. Or show an error. I think redirecting to wp login is incorrect though

**Comment by thomascoe** [comment]
With the new google login plugin the DecaturMakers will be using, the wp login page will be replaced with Google login, so the functionality in master will be correct for them. Closing this issue.
